apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
       server: https://acme-v02.api.letsencrypt.org/directory
       email: arthur.rosa@aquarelacs.com.br
       privateKeySecretRef:
         name: letsencrypt-prod
       solvers:
       - http01:
           ingress:
             class: nginx
             podTemplate:
              spec:
               nodeSelector:
                 "kubernetes.io/os": linux
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-grafana
spec:
  acme:
       server: https://acme-v02.api.letsencrypt.org/directory
       email: arthur.rosa@aquarelacs.com.br
       privateKeySecretRef:
         name: letsencrypt-prod-grafana
       solvers:
       - http01:
           ingress:
             class: nginx
             podTemplate:
              spec:
               nodeSelector:
                 "kubernetes.io/os": linux