apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquarelacs-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aquarelacs-front
  template:
    metadata:
      labels:
        app: aquarelacs-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: aquarelacs-front
        image: arthurrosa12112/react-docker
        ports:
        - containerPort: 80